name: SoycraftUtilities
author: baritone
version: 1.0
api-version: 1.20
description: a conglomerate of small plug-in related features as to not shit up /plugins with 716886 single file plugins
main: net.craftutil.Main
commands:
  tempban:
    usage: /tempban <player> <duration> <reason>
    description: bans <player> for the specified amount of time
  permban:
    usage: /permban <player> <reason>
    description: bans <player> with no expire date
  ec:
    description: Open the ender chest.
    usage: /ec
#  anon:
#    description: send an anonomized chat message
#    usage: /anon
  troll:
    description: Use a troll
    usage: /troll <player> <trolllist entry>
  trolllist:
    description: View trolls
    usage: /trolllist
  scsettings:
    description: open the soycraftUtilities settings menu
    usage: /scsettings
  banhammer:
    usage: /banhammer
    description: Gives you the banhammer
    aliases: [bh, banham, bhammer, bham]
  ipbanhammer:
    usage: /ipbanhammer
    description: Gives you the ipbanhammer
    aliases: [ih, ipham, ihammer, iham]
  kickhammer:
    usage: /kickhammer
    description: Gives you the kickhammer
    aliases: [ kh, kickham, khammer, kham ]